### ISSUE TITLE
Optimization: remove unnecessary `liftEffect`s throughout codebase

### ISSUE THREAD

**Issue by JordanMartinez** [thomashoneyman/purescript-halogen-hooks#14]
I'm pretty sure the `liftEffect` here is redundant. 
```purescript
pure $ unsafePerformEffect $ liftEffect $ Ref.modify_ fn stateRef
```
[`unsafePerformEffect`](https://pursuit.purescript.org/packages/purescript-effect/2.0.1/docs/Effect.Unsafe#v:unsafePerformEffect) takes an `Effect` as its argument and `Ref.modify_` already returns an `Effect`, so I'm not sure why `liftEffect` is there. I imagine it was from when Thomas was originally working on this code and exploring different design approaches.

**Comment by thomashoneyman** [comment]
Yes, this isn't necessary. I'm happy to accept a PR which removes these uses of `liftEffect`.
