### ISSUE TITLE
Enabling multi-Output via `Variant` and multi-Query via `VariantF`

### ISSUE THREAD

**Issue by JordanMartinez** [thomashoneyman/purescript-halogen-hooks#38]
I'm not sure how desirable this is, but I thought it would be worth raising for discussion.

Right now, a` Hooks`-based component can only emit a single message. However, if we could force the component's message type to be a `Variant`, one could define hooks that can raise their own messages 
```purescript
-- current
Hooks.raise outputToken messageValue

-- future 
Hooks.raiseV outputToken sproxy messageValue
```

A similar idea could apply to queries:
```purescript
-- current
Hooks.query queryToken queryHandler

-- future
Hooks.queryV queryToken sproxy queryHandler
```

If a Hooks-based component uses `useQuery` multiple times, only the last one is used. Thus, I don't think I can implement this idea on top of Halogen Hooks without using `unsafePerformEffect` at some point.

**Comment by thomashoneyman** [comment]
The reason a Hooks-based component only supports one type of query or output is simply because a Halogen component can only receive one type of query and raise on type of output. And that's the same reason why you can only use `useQuery` once (or, put differently, why if you use it many times only the last one is used).

Ultimately the `useQuery` gets used as the `handleQuery` function in the component, so there's not really a way to have many of them.

Put differently, are you running into something you can do in a Halogen component that you can't do with Hooks?

**Comment by JordanMartinez** [comment]
> Put differently, are you running into something you can do in a Halogen component that you can't do with Hooks?

Not at the moment. However, I do think adding more functionality might be helpful in various as-yet-unknown situations.

Correct. A component can only have one action type and one query type. However, if you forced the component's action type to be `Variant` / forced the component's query type to be `VariantF` but left the rows to be defined by the end-user, then one could define hooks that can also handle their own actions / queries.

Do I currently see a use-case for this right now? No, but the idea exists and I'm curious what would be possible if it was implemented (assuming it can be).

**Comment by thomashoneyman** [comment]
Working with `Variant` and `VariantF` is a lot more tedious than working with normal sum types for messages and queries in components. I'm hesitant to make any change that would require using them unless there were a really good reason to do so. That's even more the case given that using `Variant` or `VariantF` for these types is quite rare.

If I'm understanding you correctly, you can use event sources to emulate what you're describing. You can have an event source that emits messages from the hook to the parent component, for example.

**Comment by JordanMartinez** [comment]
Ok. I'll close this then. This idea might not be practical, and until there's a definite use-case for it, I won't really know whether it's worth it.
Thanks for your thoughts on the matter though!
