### ISSUE TITLE
Link to cookbook's Halogen Examples ported recipes

### ISSUE THREAD

**Issue by JordanMartinez** [thomashoneyman/purescript-halogen-hooks#51]
See [miles' comment about linking to the cookbook's recipes](https://github.com/JordanMartinez/purescript-cookbook/issues/138#issuecomment-658533987) since we ported the Halogen examples to a Hooks version there.

**Comment by thomashoneyman** [comment]
I’m happy to add a link in this project to the cookbook recipes for Hooks. I think it would make sense in the main README, the examples README, and the beginning of the docs.

Something like:

> To see more examples of Hooks in action, see the PureScript Cookbook’s recipes for Halogen Hooks
